# src/guide_creator_flow/crews/content_crew/config/tasks.yaml
write_section_task:
  description: >
    A well-written witty tweet should:
    1. Be concise and to the point, ideally within the 280-character limit.
    2. Include a clever or humorous twist that engages the reader.
    3. Use wordplay, puns, or clever phrasing to add wit.
    4. Be relevant to current events, trends, or relatable topics.
    5. Evoke an emotional response, such as amusement or surprise.
    6. Avoid being offensive or insensitive to any group of people.
    7. Use proper grammar and spelling to maintain readability.

  expected_output: >
    A good tweet.
  agent: content_writer

review_section_task:
  description: >
    Your review should:
    1. Fix any grammatical or spelling errors
    2. Ensure content is comprehensive and accurate
    3. Enhance the structure and flow
    4. Add any missing key information
    5. have tremendous wit
  expected_output: >
    An improved, polished version enhances clarity, accuracy, and consistency. Is not academic.
  agent: content_reviewer
  context:
    - write_section_task